Added different levels of logger
Added 5 level of loggers
1.Info : as the talker/lister logs the msg on the terminal
2.Debug: Every 20 logs this logs the rate of publisher
3.Warn: Warn is loggeg whenever there is change in publishing rate
4.Error: Error is logged whenever the subscriber is running and receives nothing on the topic
5.Fatal: Fatal is logged whenever the someone sets the publishing rate more than 100 msg/sec and program terminates